#!/bin/sh

## Removes PAM configuration in "/etc/pam.d/common-auth":
pam-auth-update --package --remove pamrfid

## Deletes compiled Python files before removing package
find /usr/lib/pamrfid/ -type f -name *.pyc -exec rm {} \;

exit $?
