#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
PAM RFID

Copyright 2015 Philipp Meisberger, Bastian Raschke.
All rights reserved.
"""

import argparse
import hashlib
import uuid
import os
from pamrfid import __version__ as VERSION
from pamrfid.Config import Config
from pyrfid.PyRfid import PyRfid


class PamRfid(object):
    """
    pamrfid configuration program.

    The PyRfid library instance
    @var PyRfid __rfid

    Config instance
    @var Config __config
    """

    __rfid = None
    __config = None

    def __init__(self):
        """
        Constructor

        """

        ## Tries to init config instance
        try:
            self.__config = Config('/etc/pamrfid.conf')

        except Exception as e:
            print('[Exception] ' + str(e))
            exit(1)

        ## Gets connection values
        port = self.__config.readString('PyRfid', 'port')
        baudRate = self.__config.readInteger('PyRfid', 'baudRate')

        ## Tries to establish connection
        try:
            self.__rfid = PyRfid(port, baudRate)

        except Exception as e:
            print('[Exception] The RFID sensor could not be initialized: ' + str(e))
            exit(1)

    def __showConfirmationDialog(self, question = ''):
        """
        Shows confirmation dialog.

        @param string question
        @return boolean
        """

        answer = raw_input(question + ' (Y/n)')
        return ( answer in ['y', 'Y', ''] )

    def addUser(self, userName):
        """
        Enrolls new RFID tag and adds user to pamrfid.

        @param string userName
        @return boolean
        """

        ## Checks if user is root
        if ( os.geteuid() != 0 ):
            print('[Error] You need to have root privileges to add a user!')
            return False

        ## Checks if the the user is not already added
        if ( self.__config.itemExists('Users', userName) == True ):
            print('[Error] The user "' + userName + '" is already added!')
            return False

        ## Confirmation dialog
        if ( self.__showConfirmationDialog('Are you sure you want to add the user "' + userName + '"?') == False ):
            print('Adding user canceled.')
            return False

        ## Tries to bind a tag to a user
        try:
            print('Waiting for tag...')

            ## Read out tag data
            if ( self.__rfid.readTag() != True ):
                raise Exception('User aborted!')

            ## Generates salt
            salt = uuid.uuid4().hex

            ## Calculates salted hash of tag
            tagHash = hashlib.sha256(salt.encode() + self.__rfid.rawTag.encode()).hexdigest()

            ## The new user information list
            userData = (
                salt,
                tagHash,
            )

            ## Adds user to configuration file
            self.__config.writeList('Users', userName, userData)

            if ( self.__config.save() == True ):
                print('The user "' + userName + '" has been added successfully!')
            else:
                raise Exception('The configuration could not be written!')

        except Exception as e:
            print('[Exception] Error while adding user: ' + str(e))
            return False

        return True

    def removeUser(self, userName):
        """
        Removes RFID tag from configuration.

        @param string userName
        @return boolean
        """

        ## Checks if user is root
        if ( os.geteuid() != 0 ):
            print('[Error] You need to have root privileges to add a user!')
            return False

        ## Checks if the the user was already added
        if ( self.__config.itemExists('Users', userName) == False ):
            print('[Error] The user "' + userName + '" is not added!')
            return False

        ## Confirmation dialog
        if ( self.__showConfirmationDialog('Are you sure you want to remove the user "' + userName + '"?') == False ):
            print('Removing user canceled.')
            return False

        ## Tries to delete tag
        try:
            ## Removes entries from configuration file
            if ( self.__config.remove('Users', userName) == True and self.__config.save() == True ):
                print('The user "' + userName + '" has been removed successfully!')
            else:
                raise Exception('The configuration file could not be written!')

        except Exception as e:
            print('[Exception] Error while removing user: ' + str(e))
            return False

        return True


if ( __name__ == '__main__' ):

    parser = argparse.ArgumentParser(description='pamrfid configuration program:')

    parser.add_argument('--add-user', metavar='NAME', help='Adds a new user.')
    parser.add_argument('--remove-user', metavar='NAME', help='Removes a user.')
    parser.add_argument('--version', '-v', action='version', version='pamrfid '+ VERSION, help='Prints version and exits.')

    args = vars(parser.parse_args())

    if ( args['add_user'] ):
        PamRfid().addUser(args['add_user'])
    elif ( args['remove_user'] ):
        PamRfid().removeUser(args['remove_user'])
    else:
        parser.print_help()
