#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
PAM RFID configuration check

Copyright 2014 Philipp Meisberger <team@pm-codeworks.de>,
               Bastian Raschke <bastian.raschke@posteo.de>
All rights reserved.
"""

import argparse
import hashlib
import uuid
import os
import ConfigParser

from pamrfid import __version__ as VERSION
from pamrfid import CONFIG_FILE
from pyrfid.pyrfid import PyRfid


class PamRfidCheck(object):
    """
    Configuration check program.

    The PyRfid library instance
    @var PyRfid __rfid
    """

    __rfid = None

    def __init__(self):
        """
        Constructor

        """

        ## Tries to read configuration
        try:
            ## Checks if path/file is readable
            if ( os.access(CONFIG_FILE, os.R_OK) == False ):
                raise Exception('The configuration file "' + CONFIG_FILE + '" is not readable!')

            self.__config = ConfigParser.ConfigParser()
            self.__config.read(CONFIG_FILE)

        except Exception as e:
            print('[Exception] ' + str(e))
            exit(1)

        try:
            ## Gets connection values
            port = self.__config.get('PyRfid', 'port')
            baudRate = int(self.__config.get('PyRfid', 'baudRate'), 10)

            ## Tries to establish connection
            self.__rfid = PyRfid(port, baudRate)

        except Exception as e:
            print('[Exception] The RFID sensor could not be initialized: ' + str(e))
            exit(1)


    def checkUser(self, userName):
        """
        Do a RFID simulation for a given user.

        @param string userName
        @return boolean
        """

        ## Checks if the the user was already added
        if ( self.__config.has_option('Users', userName) == False ):
            print('[Error] The user "' + userName + '" is not added!')
            return False

        ## Tries to get user information
        try:
            userData = self.__config.get('Users', userName).split(',')

            ## Validates user information
            if ( len(userData) != 2 ):
                raise Exception('The user information of "' + userName + '" is invalid!')

            salt = userData[0]
            expectedTagHash = userData[1]

        except Exception as e:
            print('[Exception] ' + str(e))
            return False

        ## Tries to check RFID
        try:
            print('Waiting for tag...')

            ## Read out tag data
            if ( self.__rfid.readTag() != True ):
                raise Exception('User aborted!')

            ## Show additional information
            print('------------------------')
            print('Tag ID:       ' + self.__rfid.tagId)
            print('Tag type:     ' + self.__rfid.tagType)
            print('------------------------')

            ## Calculates hash of tag ID
            print('Calculating hash...')
            tagHash = hashlib.sha256(salt.encode() + self.__rfid.rawTag.encode()).hexdigest()

            print('Checking if calculated hash matches stored hash...')

            ## Checks if read hash matches stored hash
            if ( tagHash == expectedTagHash ):
                print('Hashes match!')
                print('Check for user "' + userName + '" was successful!')
            else:
                raise Exception('The found tag is not assigned to user!')

        except Exception as e:
            print('[Exception] Check for user "' + userName + '" failed: ' + str(e))
            return False

        return True


if ( __name__ == '__main__' ):

    parser = argparse.ArgumentParser(description='PAM RFID simulation program:')

    parser.add_argument('--check-user', metavar='NAME', help='Checks RFID tag for an existing user.')
    parser.add_argument('--version', '-v', action='version', version='PAM RFID ' + VERSION, help='Prints version and exits.')

    args = vars(parser.parse_args())

    if ( args['check_user'] ):
        PamRfidCheck().checkUser(args['check_user'])
    else:
        parser.print_help()
