.TH pamrfid-check 1 "July 2014" "" "PAM RFID"

.SH NAME
pamrfid-check \- PAM RFID simulation program

.SH SYNOPSIS
.nf
.fam C
\fBpamrfid-check\fP \fB--check-user\fP NAME | [\fB--version\fP | \fB--help\fP]
.fam T
.fi

.SH DESCRIPTION
\fBpamrfid-check\fP can be used to simulate RFID authentication process for bind users.

.SH OPTIONS

.TP
.B
\fB--check-user\fR NAME
Runs check for an existing user.

.TP
.B
\fB--version\fR
Prints version and exits.

.TP
.B
\fB--help\fR, \fB-h\fR
Show summary of options.

.SH FILES
/etc/pamrfid.conf

.SH AUTHORS
Philipp Meisberger <team@pm-codeworks.de>
.br
Bastian Raschke <bastian.raschke@posteo.de>

Please send bug reports to one of those mail addresses. Visit www.pm-codeworks.de and www.sicherheitskritisch.de for more interesting projects.
